os:
  - linux

language: node_js

node_js:
  - "4"
  - "5"
  - "6"
  - "7"

script:
  - npm test

after_success:
  - npm install coveralls
  - ./node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
